# This file should contain everything to configure the workflow on a global scale.
# It should be complemented by a samples.tsv file that contains one row per sample.
# The units.tsv file should contain the location of each project folder
# (containing fastq files).

# -- 1. Samples configuration -- #
samples: "config/samples.tsv"
units: "config/units.tsv"
out: "/data/gpfs-1/users/cofu10_c/scratch/scASAP/out"
log: "/data/gpfs-1/users/cofu10_c/scratch/scASAP/log" 

# -- 2. Program configuration -- # Configure the correspondent environmental modules and program paths for version control
envmodules:
    cellranger: "/fast/groups/ag_ludwig/Modules/modulefiles/cellranger-atac/2.1.0"

# -- 3. Analysis parameters -- #
# --- a. QC --- #
fastq_screen:
      enabled: False
      index_dir: "/data/gpfs-1/users/cofu10_c/scratch/P1813/fastq_indexes"
multiqc: "--config config/multiqc_config.yaml"

# --- b. Alignment --- #
cellranger:
    reference: "/data/gpfs-1/groups/ag_ludwig/work/genome_ref/refdata-cellranger-arc-GRCh38-2020-mtMask"

# --- c. Doublet identification --- #
amulet:
    autosomes: "/data/gpfs-1/groups/ag_ludwig/work/software/AMULET/human_autosomes.txt"
    blacklist: "/data/gpfs-1/groups/ag_ludwig/work/genome_ref/ENCODE_blacklist/GRCh38_unified_blacklist.bed"

# --- d. (optional) Mitochondrial variant identification --- #
mgatk:
   enable: TRUE
mgatk-del-find:
   enable: TRUE 
# --- e. (optional) Signac --- #
signac:
  enable: FALSE
  qc:
    min_peak_width: 20
    max_peak_width: 10000
    min_counts: 500
    max_nucleosome_signal: 2
    min_TSS: 2
    min_peak_fragment: 1000
    max_peak_fragment: 25000
    min_percentage_peaks: 30
  mito:
    enable: TRUE
    min_depth: 10
    min_strand_cor: 0.65
    min_cell_var: 5
    min_VMR: 0.01
    n_cells_conf_detected: 1
    clonotype_finding:
      fc_resolution: 1
      fc_k: 10
  annotation:
    granges_ens: EnsDb.Hsapiens.v86 
    genome: "hg38"
    reference: "/data/gpfs-1/groups/ag_ludwig/work/bridge_annotation/pbmc_multimodal.h5seurat"
    haplogroup: "/data/gpfs-1/users/cofu10_c/work/references/haplotype/2023-07-15_haplogroup_simple.tsv"
  individual_analysis: TRUE
  integrate_samples: TRUE
  GEX: TRUE
  harmony:
    enable: TRUE
    lambda: 1
  clustering:
    remove_first_component: TRUE
    dims: 30
    min.cutoff: 20 # Cutoff for feature to be included in the VariableFeatures for the object.
    min.dist: 0.3
    algorithm: 3
    resolution: 0.4
  batch_correction:
    enable: TRUE
    variable_to_regress: "sample"
  cores: 4

# --- f. CNV analysis with Epianeufinder --- # 
cnv:
  enable: TRUE

# --- g. (optional) Genotyping with gotcha --- #
gotcha:
  enable: False
  whitelist: "/data/gpfs-1/users/cofu10_c/work/references/barcodes/737K-cratac-v1.txt"
  primer:
    primer_sequence: "AAAGCCTGTAGTTTTACTTACTCTCGTCTCCACAG"
    reverse_complement: TRUE
    max_mismatch: 3
  mutation:
    read: "R2"
    start: 35
    end: 38
    mut_sequence: "AAA"
    wt_sequence: "ACA"

# -- Cluster resources configuration -- #
resources:
    default:
      threads: 1
      mem_mb: 8000
      walltime: 480
    fastqc:
      threads: 4
      mem_mb: 32000
    fastq_screen:
      threads: 8
    cellranger:
      threads: 4
      mem_mb: 120000
      walltime: 4320
    mgatk:
      threads: 4
      mem_mb: 64000
      walltime: 1140
    amulet:
      threads: 4
      mem_mb: 64000
      walltime: 1140
    signac:
      threads: 2
      mem_mb: 64000
      walltime: 1140
    cnv:
      threads: 4
      mem_mb: 64000
      walltime: 1140
    gotcha:
      threads: 4
      mem_mb: 80000
